name: cuda-samples
title: CUDA Samples
version: '12.5'
summary: Samples for CUDA developers which demonstrate features in CUDA Toolkit
description: |
  NOTE: This is a wrapper of the official package, but it is not verified,
  affiliated with, or supported by NVIDIA.

  Samples for CUDA developers which demonstrate features in CUDA Toolkit.

website: https://github.com/NVIDIA/cuda-samples
contact: https://github.com/pedro-avalos/cuda-samples-snap/issues
issues: https://github.com/pedro-avalos/cuda-samples-snap/issues
source-code: https://github.com/NVIDIA/cuda-samples

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  cuda-samples:
    command: bin/launcher
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/local/cuda/lib:$LD_LIBRARY_PATH
    plugs:
      - opengl
      - network-bind
      - hardware-observe
      - home
      - removable-media

package-repositories:
  - type: apt
    architectures: [amd64]
    formats: [deb]
    path: /
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64
    priority: 600

parts:
  launcher:
    plugin: dump
    source: snap/local
    source-type: local

  glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-type: git
    source-subdir: glib-only
    plugin: make
    build-packages: [libglib2.0-dev]
    stage-packages: [libglib2.0-bin]

  cuda-samples:
    after: [glib-only]
    plugin: make
    source: https://github.com/NVIDIA/cuda-samples.git
    source-type: git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    override-pull: |
      craftctl default
      git apply --ignore-space-change --ignore-whitespace \
        $CRAFT_PROJECT_DIR/snap/local/patches/*.patch
    build-snaps: [cmake]
    build-packages:
      - cuda-toolkit
      - libegl-dev
      - libfreeimage-dev
      - libgl-dev
      - libgles-dev
      - libglfw3-dev
      - libglu1-mesa-dev
      - libglut-dev
      - libmpich-dev
      - libopenmpi-dev
      - libvulkan-dev
    stage-packages:
      - libdeflate0
      - libegl1
      - libevent-core-2.1-7t64
      - libevent-pthreads-2.1-7t64
      - libfreeimage3
      - libgl1
      - libglfw3
      - libglu1-mesa
      - libglut3.12
      - libglvnd0
      - libglx0
      - libgomp1
      - libhwloc15
      - libimath-3-1-29t64
      - libjbig0
      - libjpeg-turbo8
      - libjxr0t64
      - liblcms2-2
      - liblerc4
      - libopenexr-3-1-30
      - libopengl0
      - libopenjp2-7
      - libopenmpi3t64
      - libpsm-infinipath1
      - libpsm2-2-compat
      - libraw23t64
      - libsharpyuv0
      - libtiff6
      - libvulkan1
      - libwebp7
      - libwebpmux3
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxi6
      - libxxf86vm1
    stage:
      - -usr/lib/x86_64-linux-gnu/libEGL_mesa.so*
      - -usr/lib/x86_64-linux-gnu/libGLX_mesa.so*
      - -usr/lib/x86_64-linux-gnu/libOpenEXRCore-3_1.so*
      - -usr/lib/x86_64-linux-gnu/libOpenEXRUtil-3_1.so*
      - -usr/lib/x86_64-linux-gnu/libXfixes.so*
      - -usr/lib/x86_64-linux-gnu/libgbm.so*
      - -usr/lib/x86_64-linux-gnu/libicui18n.so*
      - -usr/lib/x86_64-linux-gnu/libicuio.so*
      - -usr/lib/x86_64-linux-gnu/libicutest.so*
      - -usr/lib/x86_64-linux-gnu/libicutu.so*
      - -usr/lib/x86_64-linux-gnu/libmana.so*
      - -usr/lib/x86_64-linux-gnu/libmlx4.so*
      - -usr/lib/x86_64-linux-gnu/libmpi_java.so*
      - -usr/lib/x86_64-linux-gnu/libmpi_mpifh.so*
      - -usr/lib/x86_64-linux-gnu/libmpi_usempi_ignore_tkr.so*
      - -usr/lib/x86_64-linux-gnu/libmpi_usempif08.so*
      - -usr/lib/x86_64-linux-gnu/libompitrace.so*
      - -usr/lib/x86_64-linux-gnu/libraw_r.so*
      - -usr/lib/x86_64-linux-gnu/libucs_signal.so*
      - -usr/lib/x86_64-linux-gnu/libwayland-client.so*
      - -usr/lib/x86_64-linux-gnu/libwayland-server.so*
      - -usr/lib/x86_64-linux-gnu/libxcb-dri2.so*
      - -usr/lib/x86_64-linux-gnu/libxcb-glx.so*
      - -usr/lib/x86_64-linux-gnu/libxcb-present.so*
      - -usr/lib/x86_64-linux-gnu/libxcb-randr.so*
      - -usr/lib/x86_64-linux-gnu/libxcb-shm.so*
      - -usr/lib/x86_64-linux-gnu/libxcb-sync.so*
      - -usr/lib/x86_64-linux-gnu/libxcb-xfixes.so*
      - -usr/lib/x86_64-linux-gnu/libxshmfence.so*
      - -usr/lib/x86_64-linux-gnu/openmpi/lib/ompi_monitoring_prof.so*

  cuda-libraries:
    plugin: nil
    build-packages: [cuda-toolkit]
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/local/cuda/lib
      cp -ar /usr/local/cuda/lib64/libcublas.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libcublasLt.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libcudart.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libcufft.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libcurand.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libcusolver.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libcusparse.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libnppc.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libnppicc.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libnppif.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libnppist.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libnppisu.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libnvJitLink.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libnvjpeg.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
      cp -ar /usr/local/cuda/lib64/libnvrtc.so* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
