name: cuda-samples
title: CUDA Samples
version: '12.5'
summary: Samples for CUDA developers which demonstrate features in CUDA Toolkit
description: |
  NOTE: This is a wrapper of the official package, but it is not verified,
  affiliated with, or supported by NVIDIA.

  Samples for CUDA developers which demonstrate features in CUDA Toolkit.

website: https://github.com/NVIDIA/cuda-samples
contact: https://github.com/pedro-avalos/cuda-samples-snap/issues
issues: https://github.com/pedro-avalos/cuda-samples-snap/issues
source-code: https://github.com/NVIDIA/cuda-samples

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  cuda-samples:
    command: bin/launcher
    plugs:
      - opengl
      - network-bind
      - hardware-observe
      - home
      - removable-media

package-repositories:
  - type: apt
    architectures: [amd64]
    formats: [deb]
    path: /
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64
    priority: 600

parts:
  launcher:
    plugin: dump
    source: snap/local
    source-type: local

  glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-type: git
    source-subdir: glib-only
    plugin: make
    build-packages: [libglib2.0-dev]
    stage-packages: [libglib2.0-bin]

  cuda-samples:
    after: [glib-only]
    plugin: make
    source: https://github.com/NVIDIA/cuda-samples.git
    source-type: git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    override-pull: |
      craftctl default
      git apply --ignore-space-change --ignore-whitespace \
        $CRAFT_PROJECT_DIR/snap/local/patches/*.patch
    build-snaps: [cmake]
    build-packages:
      - cuda-toolkit
      - libfreeimage-dev
      - libegl-dev
      - libgles-dev
      - libgl-dev
      - libglut-dev
      - libglu1-mesa-dev
      - libvulkan-dev
      - libmpich-dev
      - libopenmpi-dev
      - libglfw3-dev
    stage-packages:
      - libglu1-mesa
      - libfreeimage3
      - mpich
    override-build: |
      make
      mkdir -p $CRAFT_PART_INSTALL/usr/local/cuda-samples
      cp -ar bin/x86_64/linux/release/* \
        $CRAFT_PART_INSTALL/usr/local/cuda-samples/

lint:
  ignore:
    - library:
      - usr/lib/x86_64-linux-gnu/libGLU.so*
      - usr/lib/x86_64-linux-gnu/libOpenEXRUtil-3_1.so*
      - usr/lib/x86_64-linux-gnu/libefa.so*
      - usr/lib/x86_64-linux-gnu/libfreeimage-3.18.0.so*
      - usr/lib/x86_64-linux-gnu/libicuio.so*
      - usr/lib/x86_64-linux-gnu/libicutest.so*
      - usr/lib/x86_64-linux-gnu/libmana.so*
      - usr/lib/x86_64-linux-gnu/libmlx4.so*
      - usr/lib/x86_64-linux-gnu/libmpichcxx.so*
      - usr/lib/x86_64-linux-gnu/libmpichfort.so*
      - usr/lib/x86_64-linux-gnu/libraw_r.so*
      - usr/lib/x86_64-linux-gnu/libucs_signal.so*
