name: cuda-samples
title: CUDA Samples
version: '12.5'
summary: Samples for CUDA developers which demonstrate features in CUDA Toolkit
description: |
  NOTE: This is a wrapper of the official package, but it is not verified,
  affiliated with, or supported by NVIDIA.

  Samples for CUDA developers which demonstrate features in CUDA Toolkit.

website: https://github.com/NVIDIA/cuda-samples
contact: https://github.com/pedro-avalos/cuda-samples-snap/issues
issues: https://github.com/pedro-avalos/cuda-samples-snap/issues
source-code: https://github.com/NVIDIA/cuda-samples

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

package-repositories:
  - type: apt
    architectures: [amd64]
    formats: [deb]
    path: /
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64
    priority: 600

parts:
  launcher:
    plugin: dump
    source: snap/local
    source-type: local

  cuda-samples:
    plugin: make
    source: https://github.com/NVIDIA/cuda-samples.git
    source-type: git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    override-pull: |
      craftctl default
      git apply --ignore-space-change --ignore-whitespace \
        $CRAFT_PROJECT_DIR/snap/local/patches/*.patch
    build-packages:
      - cuda-toolkit
